# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
# Fabric Properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.18.2
# Mod Properties
mod_version=0.6.1-Beta
maven_group=net.hana.cobblemon-paleontologist
archives_base_name=cobblemon-paleontologist
# Dependencies
fabric_version=0.116.7+1.21.1
fabric_kotlin_version=1.13.4+kotlin.2.2.0
cobblemon_version=1.8.0+1.21.1

jei_version=19.27.0.340